image: 
 repository: ziel249/complete-devops-project
 tag: 33f386d
 pullpolicy: IfNotPresent
service:
 type: ClusterIP
 port: 8080
ingress: 
 enabled: false
serviceAccount:
 enabled: false
autoscaling: 
 enabled: false


