---

name: Complete DevOps Project Pipeline

on:
  push:
    branches:
      - main

jobs: 
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Bandit SAST Scan
        uses: actions/checkout@v2
      - name: Checkout código
        run: |
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
      - name: Configurar Python
        run: |
          docker build -t ziel249/complete-devops-project:${{ env.SHORT_SHA }} .
      - name: Instalar Bandit
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Ejecutar Bandit
        run: |
          docker push ziel249/complete-devops-project:${{ env.SHORT_SHA }}
      - name: Subir reporte de Bandit
        run: |
          git config --local user.email "hellow@zel743.com"
          git config --local user.name "zel743"
      - name: Django System Check
        run: |
          sed -i "s/tag:.*/tag: ${{ env.SHORT_SHA }}/" ./complete-devops-project-time-printer/values.yaml
          git add ./complete-devops-project-time-printer/values.yaml
          git commit -m "Updated image tag to ${{ env.SHORT_SHA }}"
          git push

